(function(){function C(a,c){var g=[],f;for(f in a){var h=c?c+"["+f+"]":f,k=a[f];g.push("object"==typeof k?C(k,h):encodeURIComponent(h)+"="+encodeURIComponent(k))}return g.join("&")}function L(a){if(!a||""==a)return"";for(;a&&-1<" \n\r\t".indexOf(a.charAt(0));)a=a.substring(1);for(;a&&-1<" \n\r\t".indexOf(a.charAt(a.length-1));)a=a.substring(0,a.length-1);return a}function D(a,c){function g(c,f){void 0!==a[c]||(a[c]=[]);f=f.replace(/\+/g,"%20");f=decodeURIComponent(f);a[c].push(f)}c=L(c).split("&");
for(var f=0;f<c.length;f++)if(c[f]){var h=c[f].indexOf("=");0>h?g(c[f],"1"):g(c[f].substring(0,h),c[f].substring(h+1))}}function n(a){var c=window._zero_kz_;if(void 0!==c&&"object"==typeof c)for(var g=0;g<c.length;g++)if(c[g]&&c[g][0]&&c[g][0]==a)return c[g][1]}function E(a){for(var c=("https:"==location.protocol?"https:":"http:")+"//c.zero.kz/z.png?",g=[],f=0;f<a.length;f++)g.push("object"==typeof a[f][1]?C(a[f][1],a[f][0]):encodeURIComponent(a[f][0])+"="+encodeURIComponent(a[f][1]));return c+g.join("&")+
"&"+(Math.random()+11)}function F(a){return(a=document.cookie.match(new RegExp("(?:^|;\\s*)"+a+"=([^;]*)")))&&1 in a?decodeURIComponent(a[1]):null}function G(a,c,g,f){var h="";g&&(h=new Date,h.setTime(h.getTime()+6E4*g),h=";expires="+h.toGMTString());document.cookie=a+"="+encodeURIComponent(c)+h+";path="+(f||"/")}function H(){if(!v)try{v=new Date}catch(a){}return v}function M(){var a=H();return a&&"getTimezoneOffset"in a?a.getTimezoneOffset():666}function I(a,c){var g=document.getElementById("_zero_"+
a);if(g){for(var f=g.childNodes.length-1;0<=f;f--)g.removeChild(g.childNodes[f]);var h=document.createElement("a");h.href="https://zero.kz/?s="+a;h.target="_blank";var k=document.createElement("img");k.border="0px";k.width=88;k.height=31;k.alt="ZERO.kz";k.title="ZERO.kz: Слева место в казахстанском рейтинге,\nсправа количество казахстанских просмотров в сутки,\nколичество казахстанских посетителей в сутки,\nвсех посетителей сейчас на сайте";k.src=c;k.onload=function(){g&&g.appendChild(h)&&h.appendChild(k)}}else console.warn("ZERO.kz: Containert _zero_"+
a+" not found. Use original code from ZERO.kz")}function J(a,c){"undefined"===typeof a&&(a="");var g=function(a,c){a=parseInt(a,10).toString(16);return c<a.length?a.slice(a.length-c):c>a.length?Array(1+(c-a.length)).join("0")+a:a};this.php_js||(this.php_js={});this.php_js.uniqidSeed||(this.php_js.uniqidSeed=Math.floor(123456789*Math.random()));this.php_js.uniqidSeed++;a+=g(parseInt((new Date).getTime()/1E3,10),8);a+=g(this.php_js.uniqidSeed,5);c&&(a+=(10*Math.random()).toFixed(8).toString());return a}
function N(){var a;(a=F("_zero_cc"))&&(14<a.length||13>a.length)&&(a=void 0);a=a?a:"ef88a73599fb37";1!=a&&G("_zero_cc",a,525600,"/");return a}function O(){if(x)return!1;x=!0;var a=window.location.href;a!=w&&(0!=w&&(0>=a.indexOf("#")||a.match(/#.*(=|&|\?|\/|!)/))&&(y=a,p=w,v=!1,r=K(),r.push(["if",1]),I(z,E(r))),w=a);x=!1;return!0}function K(){var a,c=[];c.push(["u",(a=n("id"),"number"==typeof a?a:0)]);c.push(["t",(a=n("type"),"number"==typeof a?a:1)]);c.push(["cc",N()]);var g=0,f=0,h=0,k=0,l=F("_zero_ss");
l&&(l=l.split("."),4==l.length&&(m=l[0],f=parseInt(l[1],10),g=parseInt(l[2],10),t=parseInt(l[3],10),m&&(14<m.length||13>m.length)&&(m=void 0)));(l=H())&&"getTime"in l&&(h=Math.round(l.getTime()/1E3),0<g&&(A=h-f,k=h-g));if(!m)m=J("",!1),f=h;else if(1800<k||0>k)B=m,m=J("",!1),t=0,f=h;t++;G("_zero_ss",m+"."+f+"."+h+"."+t,525600,"/");c.push(["s",m]);c.push(["sh",t]);0<=A&&c.push(["slt",A]);B&&c.push(["sls",B]);c.push(["d",(a=n("diff"),"number"==typeof a?a:0)]);if(a=window.screen)c.push(["wd","undefined"!=
typeof a.width?a.width:0]),c.push(["hg","undefined"!=typeof a.height?a.height:0]),c.push(["cd",a.colorDepth?a.colorDepth:a.pixelDepth]);b=[];try{a=document;var d=a.documentElement,e=a.body,q=e&&e.clientWidth&&e.clientHeight;d&&d.clientWidth&&d.clientHeight&&("CSS1Compat"===a.compatMode||!q)?b=[d.clientWidth,d.clientHeight]:q&&(b=[e.clientWidth,e.clientHeight])}catch(Q){}a=b;2==a.length&&(c.push(["w","undefined"!=typeof a[0]?a[0]:0]),c.push(["h","undefined"!=typeof a[1]?a[1]:0]));c.push(["ln",(a=window.navigator,
(a&&(a.language||a.browserLanguage)||"-").toLowerCase())]);c.push(["je",(a=window.navigator,a&&a.javaEnabled()?1:0)]);c.push(["cs",(a=document,a.characterSet||a.charset||"-")]);c.push(["ce",(a=window.navigator,a&&a.cookieEnabled?1:0)]);a=[];d=window._zero_kz_;if(void 0!==d&&"object"==typeof d)for(e=0;e<d.length;e++)d[e]&&d[e][0]&&"add"==d[e][0]&&a.push(d[e]);for(d=0;d<a.length;d++)a[d]&&3<=a[d].length&&c.push([a[d][1],a[d][2]]);n("iframe")&&(y=p,p=null,c.push(["if",1]));window!=window.top&&c.push(["fi",
1]);c.push(["du",y]);if(p){c.push(["rf",p]);a=p;e={url:a,protocol:"http",host:"",path:"",params:{},anchor:""};a&&(d=a.indexOf("://"),0<=d&&(e.protocol=a.substring(0,d),a=a.substring(d+3)),d=a.search("/|\\?|#"),0<=d?(e.host=a.substring(0,d).toLowerCase(),"."==e.host.charAt(e.host.length-1)&&(e.host=e.host.substring(0,e.host.length-1)),a=a.substring(d),d=a.indexOf("#"),0<=d&&(e.anchor=a.substring(d+1),a=a.substring(0,d)),d=a.indexOf("?"),0<=d&&(D(e.params,a.substring(d+1)),a=a.substring(0,d)),e.anchor&&
D(e.params,e.anchor),a&&"/"==a.charAt(0)&&(a=a.substring(1)),e.path=a):(e.host=a.toLowerCase(),"."==e.host.charAt(e.host.length-1)&&(e.host=e.host.substring(0,e.host.length-1))));urlComponents=e;a:{a=urlComponents;e=P;for(q=0;q<e.length;++q)if(d=e[q].split(":"),-1<a.host.indexOf(d[0].toLowerCase())&&d[1]in a.params){e=a.params[d[1]];a=[a.host,"object"==typeof e?e&&0<e.length?e[0]:"":e,d[0]+":"+d[1]];break a}a=[]}3==a.length&&(c.push(["seh",a[0]]),c.push(["seq",a[1]]),c.push(["sem",a[2]]))}c.push(["tz",
M()]);c.push(["dt",document.title.substring(0,255)]);return c}var m,B,A=0,t=0,y=window.location.href,p=document.referrer,w=!1,x=!1,P="360.cn:q about.com:terms affiliates.quintura.com:request akavita.by:z alice:qs all.by:query alltheweb.com:q altavista.com:q aol:q aol:query aport.ru:r ask:q auone:q avg:q babylon:q baidu:wd baidu:word biglobe:q bigmir.net:q bing:q centrum.cz:q cnn:query comcast:q conduit:q daum:q ekolay.net:q eniro:search_word gde.ru:keywords globo:q go.km.ru:sq google:q goo.ne:MT haosou.com:q incredimail:q index.online.ua:q kvasir:q liveinternet.ru:ask lycos:q lycos:query mail.ru:q mamma.com:query metabot.ru,st meta.ua:q msn:q mynet.com:q najdi:q naver:query nigma.ru:s onet:q onet:qt online.onetcenter.org:qt ozu.es:q pchome:q poisk.ru:text qip.ru:query rakuten:qt rambler:query rambler:words search.bigmir.net:z search.com:q search.i.ua:q search.netscape.com:query search-results:q search.smt.docomo:MT search.ua:q search.ukr.net:search_query search.virgilio.it:qs sesam.no:q seznam:q sm.aport.ru:r so.com:q sogou:query startsiden:q szukacz.pl:q terra:query tut.by:query ukr:q virgilio:qs voila.fr:rdata web20.a.ua:query webalta.ru:q wp.pl:szukai yahoo:p yahoo:q yam.com:k yandex:text".split(" "),
v,r=[],z=n("id");if(z){r=K();I(z,E(r));var u=n("url_watcher");(u="number"==typeof u?u:0)&&setInterval(O,100<u?u:100)}})();
